### ISSUE TITLE
add npm support

### ISSUE THREAD

**Issue by kemaldaggen** [jotform/css.js#1]

**Comment by RamonGebben** [comment]
This can be done very easily. Want a PR for this or do you wanna explore that path yourselves?
[Consult this guide to help you on your way](https://docs.npmjs.com/misc/developers)

**Comment by kemaldaggen** [comment]
If you feel like, please be our guest and send a pull request. We are open to contributions. :)

We solely use this in browser environment, but I thought that it might come handy for some other purposes to parse CSS in node. So I created this issue :)

**Comment by RamonGebben** [comment]
I could send a PR when I made the repo ready, but you would need to run the npm publish since it's your code man ;)
[And a node version does exist. ](https://github.com/reworkcss/css)

[I read the article about the development process](https://medium.com/jotform-form-builder/writing-a-css-parser-in-javascript-3ecaa1719a43) and now I'm think you could have just sent it to node and let it return the JSON object via AJAX and use that library to do what you wanted. 

But then again I prefer client side so thanks for making this. :)

**Comment by ctsstc** [comment]
I would love to include this in my webpack, I know right now I could include the git repo in my project, but it would be nice to have it up on npm since npm cli seems to have some oddities with uninstalling git resources currently. I would also love to see this in ES modules.

**Comment by eeertekin** [comment]
Hey @ctsstc,

NPM module is published 

https://www.npmjs.com/package/jotform-css.js
