### ISSUE TITLE
Does css.js care about specificity?

### ISSUE THREAD

**Issue by corysimmons** [jotform/css.js#13]
https://github.com/closingtag/calc-polyfill#specificity

If not, what are the chances of getting it integrated? Is there a technical limitation?

**Comment by kemaldaggen** [comment]
Hi corrysimmons, no css.js do not have any means to identify specificity of parsed css rules. All css.js does that it takes a CSS string as input and returns a data structure, representing the CSS string. So that you can easily traverse it, modify it and compile back to CSS string.

Can I ask what do you have in your mind as use case for having CSS specificity in a CSS parser? 

Thanks.

**Comment by corysimmons** [comment]
That link I posted is exactly what I have in mind.

It's not a big deal though. Thank you. =)
